integration/\nE2E tests -> application/\nService tests
integration/\nE2E tests -> domain/\nDomain tests
integration/\nE2E tests -> infrastructure/\nInfrastructure tests
application/\nService tests -> domain/\nDomain tests
infrastructure/\nInfrastructure tests -> domain/\nDomain tests
